name: Deploy to Production

on:
  push:
    branches:
      - main  # or your production branch
  workflow_dispatch:  # allows manual trigger

env:
  DOCKER_IMAGE: rezentry-app
  DOCKER_CONTAINER: rezentry-prod
  DOCKER_CONTAINER_TEMP: rezentry-prod-temp

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:buildcache,mode=max

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DOCKER_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        run: |
          # Deploy script
          ssh $VPS_USER@$VPS_HOST << 'ENDSSH'
            # Pull the new image
            docker pull $DOCKER_IMAGE_TAG

            # Check if temp container exists and remove it
            if [ "$(docker ps -aq -f name=$DOCKER_CONTAINER_TEMP)" ]; then
              docker rm -f $DOCKER_CONTAINER_TEMP
            fi

            # Start new container on a different port
            docker run -d \
              --name $DOCKER_CONTAINER_TEMP \
              -p 3001:80 \
              $DOCKER_IMAGE_TAG

            # Wait for the new container to be healthy
            sleep 10

            # Check if the new container is running
            if [ "$(docker ps -q -f name=$DOCKER_CONTAINER_TEMP)" ]; then
              # Stop and remove the old container
              if [ "$(docker ps -aq -f name=$DOCKER_CONTAINER)" ]; then
                docker rm -f $DOCKER_CONTAINER
              fi

              # Rename the temp container to the production name
              docker rename $DOCKER_CONTAINER_TEMP $DOCKER_CONTAINER

              # Update nginx reverse proxy or load balancer configuration
              # This assumes you have nginx set up as a reverse proxy
              echo "
              upstream rezentry_backend {
                server localhost:3000;
              }

              server {
                listen 80;
                server_name your-domain.com;

                location / {
                  proxy_pass http://rezentry_backend;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
                }
              }" | sudo tee /etc/nginx/sites-available/rezentry

              # Reload nginx configuration
              sudo nginx -t && sudo systemctl reload nginx

              echo "Deployment successful!"
            else
              echo "New container failed to start. Rolling back..."
              docker rm -f $DOCKER_CONTAINER_TEMP
              exit 1
            fi
          ENDSSH
